# Generated by Django 4.2 on 2023-04-28 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0003_alter_category_options_category_level_category_lft_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
    ]
