# Generated by Django 4.2 on 2023-05-05 08:21

import My_EShop.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0004_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/', validators=[My_EShop.core.validators.validate_max_image_size]),
        ),
        migrations.AddField(
            model_name='category',
            name='category_image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/', validators=[My_EShop.core.validators.validate_max_image_size]),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default='', max_length=400, null=True),
        ),
    ]
