# Generated by Django 4.2 on 2023-04-08 19:11

import My_EShop.core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eshopuser',
            name='first_name',
            field=models.CharField(default=1, max_length=30, validators=[django.core.validators.MinLengthValidator(2), My_EShop.core.validators.validate_only_letters]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eshopuser',
            name='last_name',
            field=models.CharField(default='1', max_length=30, validators=[django.core.validators.MinLengthValidator(2), My_EShop.core.validators.validate_only_letters]),
            preserve_default=False,
        ),
    ]
